using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using EindProjectBusinessModels;
using System.Reflection;

namespace EindProjectDAL
{
    class DalMethodes
    {
        // Verijsten
        //1.1.1 Toevoegen van een werknemer     *
        //1.2.1. Toevoegen van een team         *
        //1.2.2 Beheren teamverantwoordelijken  *
        //2.1 Toevoegen van jaarlijkse verloven *
        //2.3.1.1 indien van verlofaanvragen met geldige gegevens en voldoende verlofdagen  *
        //2.3.3 Goedkeuren van verlofaanvragen door teamverantwoordelijken                 * 
        //2.3.5 afkeuren van verlofaanvragen

        //1.1.1 Toevoegen van een werknemer
        public void VoegWerknemerToeAanDb(Werknemer werknemer)
        {
            /*
             * David 16/02/15
             * Werknemer wordt uniek bepaald door personeelsnummer (autogenerated)
             * 2x zelfde werknemer is dus mogelijk en dient niet opgevangen te worden
             * annotations vangen het meeste op.
             * controle of geboortedatum realistisch is => setter 
            */
             using (DbEindproject db = new DbEindproject())
             {
                 db.Werknemers.Add(werknemer);
             }
        }

        public List<Werknemer> VraagAlleWerknemersOp()
        {
            return new List<Werknemer>();   // todo
        }

        public List<Werknemer> VraagWerknemerOp(string naam, string voornaam, int personeelsNr)
        {
            //op naam sorteren.
            return new List<Werknemer>(); // todo
        }

        public void WijzigWerknemerProperty(Werknemer werknemer)
        {

            return;
        }

        //1.2.2 Beheren teamverantwoordelijken
        public void VoegTeamToeAanDb(Team team)
        {
            /*
             * David 16/02/15
             * Team wordt bepaald door autogenerated key (Code)
             * zelfde omschrijving kan en dient niet opgevangen (dixit Ann)
            */
            using (DbEindproject db = new DbEindproject())
            {
                    db.Teams.Add(team);
            }
        }


        //1.2.2 Beheren teamverantwoordelijken
        public void BeheerTeamVerantwoordelijke(Team team)
        {

        }
        public List<Werknemer> GeefTeamleden(Team team)
        {
            return new List<Werknemer>();
        }

        //2.1 Toevoegen van jaarlijkse verloven *
        public void SetVerlofWerkNemer(Werknemer werknemer, int verlofDagen, int jaar)
        {

        }

        //2.3.1.1 indien van verlofaanvragen met geldige gegevens en voldoende verlofdagen 
        public Aanvraagstatus IndienenVerlofaanvraag(Werknemer werknemer, VerlofAanvraag verlofaanvraag)
        {
            return Aanvraagstatus.Goedgekeurd;
        }

        //2.3.3 Goedkeuren van verlofaanvragen door teamverantwoordelijken      
        //2.3.5 afkeuren van verlofaanvragen
        public void WijzigStatusVerlofaanvraag(VerlofAanvraag verlofaanvraag, Aanvraagstatus status)
        {

        }







    }
}
